name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento
    permissions: #serve para gerarmos a tag e escrever no repo
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
          relase-branch: main
          prefix: v
      # o numero versoes e gerado com base no texto do commit feature minor, breaking major etc olhar a documentacao

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # usa o token automatico de quem esta executado o pipe e preciso em caso de alteracoes no repo
          #steps.version.outputs.version pega as saida de algum passo pelo seu id
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
        # coloca uma condicao nesse caso esse pipe for gerado na branch main

  backend-build-and-test:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: ./src/api/packages.lock.json

      - name: Restore
        run: |
          dotnet restore ./src/Todo.Api.sln

      - name: Build
        run: |
          dotnet build --no-restore ./src/Todo.Api.sln --configuration Release

      - name: Test
        run: |
          dotnet test ./src/Todo.Api.sln --no-build --no-restore --configuration Release --logger tr --results-directory "TestResults"

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults


  frontend-build-and-test:
    # faz com q nunca execute esse trecho
    if: false
    runs-on: ubuntu-latest
    name: Build Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: ./src/api/packages.lock.json

      - name: Build and Test
        run: |
          dotnet restore ./src/Todo.Api.sln
          dotnet build --no-restore ./src/Todo.Api.sln

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: ./src/web

      - name: Install dependencies
        working-directory: ./src/web
        run: |
          npm install
          npm run build